### ISSUE TITLE
Javascript / JQuery functions like Toggles don't seem to be working

### ISSUE THREAD

**Issue by jurb** [jeblister/kube#1]
I'm not sure if this is a bug (so apologies in advance if I'm missing something), but it seems like some functions like Toggleme don't work on my served hugo site loaded with the Kube theme. I test this by copying over the example site and loading http://localhost:1313/docs/toggleme/.  I'm not seeing anything happening in the console either.

It seems to work on the 'normal' Kube site, here: https://imperavi.com/kube/docs/toggleme/.

**Comment by jeblister** [comment]
Thank you @jurb 
Yes it was a issue.
In the last commit i fixed the bug with the Toggleme function.

**Comment by jurb** [comment]
@jeblister Looking at your commit, I now see I just had to remove `data-loaded="true"`, which was in the source code, but (corectly) not featured in your documentation. I could've looked better! :) Thanks a lot for fixing the documentation!
