### ISSUE TITLE
Failed on loading resources

### ISSUE THREAD

**Issue by ceduquey** [jeblister/kube#2]
Hi, 

By using the public folder to upload the page to GitHub pages, the CSS, images, and js resources are not loading completely. 
You could check it out (by now) on https://ceduquey.github.io/pruebaKube/
![kube resources error](https://cloud.githubusercontent.com/assets/2680244/25729813/783c14fc-30fd-11e7-83df-fd21c77eb6ff.png)

I'm still checking where the error could come from, i'm opening the issue by now!

**Comment by jeblister** [comment]
Hi,
You have to add the content of the static folder to your preabaKube folder.
Otherwise use the `Hugo` command to generate the public folder for your site.

Thanks.

**Comment by ceduquey** [comment]
Hi, 
I'm sorry while trying some alternatives I should have taken out, but the files were there. 
I found that the issue is on the .../themes/kube/layouts/baseof.html
The paths right now are like this:
`<link href="/css/font.css" rel="stylesheet" type="text/css">`
And it should have at least the " . "
`<link href="./css/font.css" rel="stylesheet" type="text/css">`

That's one workaround.

**Comment by jeblister** [comment]
Hi,
I'm happy that your workaround solution work.
For me i set always my `config.yaml` variables as so : 
```
baseURL = "/"
theme = "kube"
```
to deploy the  `public` folder generated by hugo on any web hosting provider.

**Comment by ceduquey** [comment]
ok noted! 
will keep that in mind when using another hosting
thanks! for your time and this awesome theme!
