### ISSUE TITLE
Docs - Events

### ISSUE THREAD

**Issue by DigiJo** [jeblister/kube#4]
Hi

Love the theme.

I plan on offering free events to my community and this theme would be perfect if I could change docs - events. Is this possible? If I changed:

Front Matter Folder - Docs to Events
Sections - Docs to Events
Config - Main Menu: Docs to Events

If I changed these, would it work? Apologies if this question is a little elementary. My ultimate goal is instead of offering docs, on the docs page, offering events.

**Comment by jeblister** [comment]
Yes. it's going to work.

If you require any further information,  do not hesitate to contact me.
