### ISSUE TITLE
Cannot override single.html

### ISSUE THREAD

**Issue by vinamelody** [jeblister/kube#5]
Hi, I've been trying to use / override `single.html` but it always render from `_default/single.html`. Did i miss something?

i create a menu like this in `config.toml`:
```
[[menu.main]]
    name = "Download"
    weight = -100
    url = "/download/"
```
under `project name/layouts`, create folder `download` and `download/single.html`

`single.html` is similar like other template:

```
{{ define "title"}} {{ .Title}} {{end}}
{{ define "header"}} {{ partial "header" .}} {{ end }}
{{ define main }}
<div id="main">
    <div class="row">
        <div class="col col-6">
            <img src="/img/download.png"/>
        </div>
        <div class="col col-6">
            <h1>{{.Title}}</h1>
            <p>{{.Description}}</p>
            <h2>hskcjd</h2>
        </div>
    </div>
</div>
{{ end }}
{{ define "footer"}} {{ partial "footer" .}} {{end}}
```

under `project name/content/download.md`

```
+++
title = "Download"
description = "The sky is the limit only for those who aren't afraid to fly!"
draft = false

+++
```

Thanks for helping!

**Comment by vinamelody** [comment]
My bad! after few hours debugging i missed 2 things!
Let me share the solution:

1. In my `single.html`, I missed the double quote
```
{{ define main }} should be {{ define "main" }}
```

2. In my `download.md` i should add the `type`.
This is after i read this page https://gohugo.io/templates/content/ 

```
+++
title = "Download"
description = "The sky is the limit only for those who aren't afraid to fly!"
draft = false
type = "download"
+++
```

**Comment by jeblister** [comment]
:+1:
