### ISSUE TITLE
Google verification code is not working

### ISSUE THREAD

**Issue by phaya** [jeblister/kube#7]
Hi

I have included a google analytics code in config.toml, as it is indicated in the documentation:
[params.seo.webmaster_verifications]
  google = "UA-mygooglecode-X" # Optional, Google verification code

but it is not working. I have checked that no code has been generated in the public folder files that include the Google verification code. There is no google analytics javascript code as well.  

I have checked that the google code is correct, and it works if I manually included the code.

Thank you very much in advance.

Best

**Comment by jeblister** [comment]
The Google verification code is to just to verify you as the domain owner.
In this theme it generate a code in the header like that :
<meta name="google-site-verification" content="G8aBi6AH-NsfhjgfkhfgfgfghfgkhfhgY9POh4">

**For google analytics :** Hugo ships with internal templates for Google Analytics tracking, you need to provide your tracking id in your configuration file:
googleAnalytics = "UA-123-45"

and then include the Google Analytics internal template:

{{ template "_internal/google_analytics.html" . }}
See the the Hugo documentation for more : https://gohugo.io/templates/internal/#google-analytics

**Comment by phaya** [comment]
Thank you very much for your soon response!
